### PR TITLE
fix: api host, port and protocol

### PR DESCRIPTION
**Pull request by hacdias**
WIP.

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Is this linked to #611 ?

**Comment by hacdias** [comment]
Yes @koalalorenzo

**Comment by hacdias** [comment]
Does it work with your setup @koalalorenzo ?

**Comment by koalalorenzo** [comment]
I had no time to test it, but I will check it today or tomorrow. I hope that this will make to the next release (0.4.14)

**Comment by koalalorenzo** [comment]
I am not really able to test this as I need to modify the source code here: https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go#L4 and deploy it with a valid certificate for https.

**Comment by danieldaf** [comment]
Hi, I made a fix to this in another pull request (#664)

**Pull request closed without merging**
