### PR TITLE
Add Portuguese i18n support

### PR DESCRIPTION
**Pull request by mauriciomelo**
🌐 🇧🇷 🇵🇹🇦🇴 🇨🇻 🇹🇱 🇬🇶 🇬🇼 🇲🇿 🇸🇹 🌐

### CODE REVIEW

**Comment by hacdias** [comment]
Hello @mauriciomelo. Thanks!! I appreciate your effort, but could I just ask you to change it to 'pt-br'? We still don't have an European variant, but it will be made soon 😄

**Comment by mauriciomelo** [comment]
Sure, I'll update it ASAP.

**Comment by olizilla** [comment]
What needs to happen to make this mergeable @hacdias ? is it just a file rename?

**Comment by hacdias** [comment]
@olizilla I would just prefer to have it explicitly saying this was Brazilian variant but since we don't have an European translation, let's stick with this. Merging!!! ⛵️

**Pull request merged**
