### PR TITLE
[WIP] Implement Redux

### PR DESCRIPTION
**Pull request by dignifiedquire**
## The big todo - Or what needs to happen and where you can help

In general the webui (after this PR) will have six pages under which I will structure the content
### Home
- [x] Containers
  - [x] Implement
  - [ ] Test
- [x] Components
  - [x] Implement
  - [x] Test
- [x] API Calls
  - [x] Implement
  - [x] Test
- [x] Reducers
  - [x] Implement
  - [x] Test
- [x] Sagas
  - [x] Implement
  - [x] Test
#### WorldMap
- [x] Containers
  - [x] Implement
  - [ ] Test
- [x] Components
  - [x] Implement
  - [ ] Test
- [x] API Calls
  - [x] Implement
  - [x] Test
- [x] Reducers
  - [x] Implement
  - [x] Test
- [x] Sagas
  - [x] Implement
  - [x] Test
#### PeersTable
- [x] Containers
  - [x] Implement
  - [ ] Test
- [x] Components
  - [x] Implement
  - [ ] Test
- [x] API Calls
  - [x] Implement
  - [x] Test
- [x] Reducers
  - [x] Implement
  - [x] Test
- [x] Sagas
  - [x] Implement
  - [x] Test
### Files

This should be based on the 0.4 files api, dropbox style like in #221 started
- [ ] Containers
  - [ ] Implement
  - [ ] Test
- [ ] Components
  - [ ] Implement
  - [ ] Test
- [ ] API Calls
  - [ ] Implement
  - [ ] Test
- [ ] Reducers
  - [ ] Implement
  - [ ] Test
- [ ] Sagas
  - [ ] Implement
  - [ ] Test
### DAG Browser
- [ ] Containers
  - [ ] Implement
  - [ ] Test
- [ ] Components
  - [ ] Implement
  - [ ] Test
- [ ] API Calls
  - [ ] Implement
  - [ ] Test
- [ ] Reducers
  - [ ] Implement
  - [ ] Test
- [ ] Sagas
  - [ ] Implement
  - [ ] Test
### Config

This should have an option to edit the raw config, as well as generate a form using [redux-form](https://github.com/erikras/redux-form) 
- [x] Containers
  - [x] Implement
  - [x] Test
- [x] Components
  - [x] Implement
  - [x] Test
- [x] API Calls
  - [x] Implement
  - [x] Test
- [x] Reducers
  - [x] Implement
  - [x] Test
- [x] Sagas
  - [x] Implement
  - [x] Test
### Logs
- [x] Containers
  - [x] Implement
  - [ ] Test
- [x] Components
  - [x] Implement
  - [ ] Test
- [x] API Calls
  - [x] Implement
  - [x] Test
- [x] Reducers
  - [x] Implement
  - [x] Test
- [x] Sagas
  - [x] Implement
  - [x] Test
### Home

screen shot 2016-02-09 at 17 44 16
### Peers

screen shot 2016-02-15 at 23 39 16
### Logs

screen shot 2016-02-09 at 21 50 41

### CODE REVIEW

**Comment by suisha** [comment]
Hey, would you mind leaving a list of files you'd like to be tested? It doesn't have to be complete or comprehensive, I'm just not sure which files here are good to go and which still need changes to be made. I don't want to write a test for a file that's going to get rewritten.

**Comment by dignifiedquire** [comment]
@suisha sure thing, all the visual components in `app/scripts/components` need tests at the moment

**Comment by suisha** [comment]
I'm going to try implementing the config page. :construction_worker:

**Comment by dignifiedquire** [comment]
@suisha great, see #259 for some more details and let me know if you have any questions :)

**Comment by harlantwood** [comment]
From the checkboxes it looks like certain features are done already.  Would it make sense to merge these to master, and do the further features in new PRs?

**Comment by dignifiedquire** [comment]
@harlantwood not sure if that is possible, as the other things are not currently working in that branch. Might be possible to grab some old things and integrate them though to make that happen

**Comment by harlantwood** [comment]
Sure, just throwing out an idea.

**Comment by dignifiedquire** [comment]
I have just pushed a dependency locked down version using `yarn` which fixes it so it runs again with the current ipfs version

**Comment by dignifiedquire** [comment]
Current visuals:

screen shot 2017-03-09 at 14 14 27

**Comment by gerd2002** [comment]
Very nice Peers page, the current one is kind of messy.

**Comment by diasdavid** [comment]
@dignifiedquire mind sharing with @hacdias what you were doing here?

**Comment by dignifiedquire** [comment]
@diasdavid I am not sure what you are asking

**Comment by diasdavid** [comment]
@dignifiedquire is this PR still part of the plan? If so, since there are so many merge conflicts, can you list the thing you intended to do so that they can be achieved by parts?

**Comment by hacdias** [comment]
@olizilla I see you are going through all PRs. This one seems to be stale for soooo much time. I think it could be finally closed since the new efforts are on revamp branch.

**Comment by olizilla** [comment]
I'm picking the peers work from this PR, but it's ok, I know where to find it.

**Pull request closed without merging**
