### PR TITLE
fix: a11y issues in files page

### LINKED ISSUE #1498: Files screen content only semi-functional with a screen reader
**Describe the bug**

I'm visually impaired, so need to access the destkop app with  a screenreader called voiceover  in the case of mac os. You will need to hit command plus f5 to access voiceover from anywhere.
**To Reproduce**
1. launch voiceover
2. launch the ipfs app
3. click the status menu, or what they I think call the extras menu, the thign where all the icons for dropbox and yoru time are.
4. click files
5. try and use voiceover only to access the files area. . do not use a moniter.
**Expected behavior**
I should be able to navigate all controls using the curser and arrow keys.
**Screenshots**

**Desktop (please complete the following information):**

mac os 10.15  ips Revision 1b58b62
**Smartphone (please complete the following information):**

**Additional context**
 If you need a demo  of how voiceover works, please let me know.

### PR DESCRIPTION
**Pull request by rafaelramalho19**
fixes #1498

Impacted areas:
- Changed clickable items that were not-buttons to buttons.
- Added eslint plugin to prevent further a11y issues
- Fixed keyboard navigation all across the webui
- Added missing labels for important items

Any questions or concerns please raise them 😄

### CODE REVIEW

**Comment by lidel** [comment]
I'll look at E2E.

**Comment by rafaelramalho19** [comment]
@lidel thank you so much for checking that up and fixing it 😄 

Related to your demo, it looks like you're using React-virtualized table arrow navigation, which I have no control over (you're using arrow down & up instead of tab).

There's some fixes related with improving tab navigation on the webui as a whole that I want to do when I have the time 😓

**Comment by rafaelramalho19** [comment]
The arrow navigation is being handled on a separate branch, so don't worry about it 😄

**Comment by lidel** [comment]
@rafaelramalho19 is this ready for final review, or do you want to add anything?

**Comment by rafaelramalho19** [comment]
> @rafaelramalho19 is this ready for final review, or do you want to add anything?

It's good for final review 👌

**Comment by jessicaschilling** [comment]
+1 on the menu order. Thank you so much for the careful review, @lidel.

**Comment by rafaelramalho19** [comment]
Nice catch @lidel , will fix it now 😄

**Comment by rafaelramalho19** [comment]
@lidel @jessicaschilling you like this order? https://i.imgur.com/AZMDSWT.png

Fixed uncentered buttons across the app, it was due to me forgetting to check all the buttons after removing the text-align: center property 😅

**Comment by jessicaschilling** [comment]
Should we swap download and pin?

**Comment by rafaelramalho19** [comment]
> Should we swap download and pin?

Here's how it looks: https://i.imgur.com/gpr4DEB.png

**Comment by jessicaschilling** [comment]
I like that if @lidel is good with it. Thanks!

**Comment by lidel** [comment]
Note to self: I suspect CI will be fixed by #1521 – rebasing this PR should help.

**Pull request merged**
