### PR TITLE
Feat/files progress feedback

### LINKED ISSUE #1206: Display progress status while importing files
I use ipfs-desktop 0.8.0.0 (and go-ipfs 0.4.21) on Windows 10. 
When I add a file (or multiple files) by drag-and-drop in the files section of the desktop app, there is no indication about the progress, although it can take a while on my computer if the size of the file is big.

It would be great to have a progress dialog with the details of the process (bytes transferred, percentage, speed, etc.), just like when you copy files using a file manager.

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Resolves #1206

UI context information: https://www.figma.com/file/BQjzJcaKuNrNgeDnoZ664D/Web-UI-upload%2Fdownload-progress?node-id=0%3A1

Here's a video showing the current status:
https://dl.dropboxusercontent.com/s/a94hwolhhtjb8bn/TQQGFkhNpF.mp4

### Questions

- @jessicaschilling what do you think about the UI? Anything you would want changed?

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@rafaelramalho19 This is great, thank you so much! A few thoughts below.
- It's tough from the video to see in-progress state; is it possible to screenshot?
- Can we please style file icons to match how they appear in the main files list? I'm sorry if I wasn't clear about that in the black/white wireframes; I can provide high-fidelity wireframes in future if you'd rather, it just takes a little longer. (I don't know how tough it'll be to match the actual icon to the file type in the import feedback ... if that's too much we could just use generic file/folder icons that match the main files window, but would definitely be better if it could accurately reflect what the user will see in the main files window once they're uploaded.)
- Can the both the main border and the dividers in the import area please be the same gray as the dividers in the main files screen? 
- Ditto text colors to match, please: black text should be the dark gray as it appears in file names in main files screen, gray text should be the lighter gray from main files screen.
- Can the background behind "Imported x files" please be the same color as what's behind the browse bar at the top of the screen?
- Finally - I realize we didn't create an affordance for the user to close the import feedback. First inclination would be to add the X icon to the right of the expand/collapse chevron, but I'm a little concerned that might read as "cancel all the imports". If it's possible to see a screenshot of the in-progress state, that might help to clarify a bit.

Thanks again!

**Comment by rafaelramalho19** [comment]
1. It is kinda hard to see the progress status due to the redux bug I told you earlier. But here it is: https://dl.dropboxusercontent.com/s/qdcsdu964yww7c8/2XiwW54lpG.mp4

2. Styled the icons with the same color, however, I don't currently have the information to decide what type of icon to show (only if it's a folder or file). If you find it important, I'll try to investigate further on how to achieve that. https://i.imgur.com/8SKLGik.png

3. Like so? https://i.imgur.com/dOWRgD7.png

4. Changed the colors, like this? https://i.imgur.com/fac96TE.png

5. Done: https://i.imgur.com/RRjk8vn.png

6: Do you like this interaction and UI? https://dl.dropboxusercontent.com/s/yzrg6ag7kfz3w3z/6UQusRifgh.mp4

**Comment by rafaelramalho19** [comment]
@jessicaschilling done https://i.imgur.com/hbIWJ3E.png

**Comment by jessicaschilling** [comment]
Awesome, thanks!

**Comment by jessicaschilling** [comment]
Awesome, thanks!

**Comment by rafaelramalho19** [comment]
@lidel does this cover all your suggestions?
image

Moving the progress bar to the top of the selection info is possible, but it involves adding calculations of the offsetHeight + adding event listeners for resizing, and that decreases performance. 

But if you and @jessicaschilling think that it's worth it, I'll do it 😄

**Comment by jessicaschilling** [comment]
I’m not terribly bothered by the positioning of the progress bar, since it’s indefinite progress right now. Might want to revisit once we have the opportunity for actual progress? But I’ll defer to @lidel.

**Pull request merged**
