### PR TITLE
feat: navbar width toggle

### PR DESCRIPTION
**Pull request by olizilla**
Click on the logo to collapse the side nav. Click again to get it back. Invision design here: https://projects.invisionapp.com/d/main#/console/13924274/294213563/preview

ipfs-webui-nav-collapse

(the weirdness with the light blue top bar is just an artefact from the gif screen recorder.)

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
@fsdiogo strongly agree. I'll add something that appears when you hover over the nav.

**Comment by olizilla** [comment]
(in another PR tho)

**Comment by fsdiogo** [comment]
Awesome 👌

We can think of something cool 😎

**Comment by hacdias** [comment]
I'm merging this. I have a way to fix the size of the action bar bellow.

**Pull request merged**
