### PR TITLE
epic: pinning services

### LINKED ISSUE #1403: Sort order is lost when unpinning an item
**Describe the bug**
While trying to unpin several large CIDs, I foudn that there is no "unpin all" batch option and that the sort order is lost, so trying to sort your pins to show the largest first and unpin them is a painful experience, see:

ipfs-desktop-pin-sort

**Expected behavior**
- an unpin option is available in batch action at the bottom when multiple are selected
- unpinning a single item does not re-sort the list.

### LINKED ISSUE #1404: Unpinning one item initiates a full refresh of the pin-list
**Describe the bug**
When one item of the list of pins is unpinned, the UI initiates a full refresh of the pin-page, which takes a lot of time.

**Expected behavior**
The UI understands that unpinning one item from the "root" of pins will just remove the item from the list, and hide it, and work with the delta data until the next refresh is initiated.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Version 79

**Additional context**
Probably related to https://github.com/ipfs-shipyard/ipfs-webui/issues/1403

### PR DESCRIPTION
**Pull request by lidel**
**Edit 27 October: Current plan is to merge this into master sooner rather than later to not block other work — this will require detecting pinning service support (https://github.com/ipfs-shipyard/ipfs-webui/issues/1680) and removing/amending UI elements in cases where it isn't present.**

> this is draft PR to see how potential merge of https://github.com/ipfs/ipfs-gui/issues/91 looks like :crossed_fingers: 

cc @jessicaschilling @rafaelramalho19 

Closes #1404 (UI for raw pins removed)
Closes #1403 (UI for raw pins removed)

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Some of these are caused by migrating i18n keys -- happy to jump on a quick call and resolve together. LMK.

**Comment by jessicaschilling** [comment]
@rafaelramalho19 What's the latest with this?

**Comment by rafaelramalho19** [comment]
> @rafaelramalho19 What's the latest with this?

This will be a long lasting PR, since it's the epic that will contain all features. Currently we're splitting all work done into separate PRs to become easier to review

**Comment by lidel** [comment]
Continued in https://github.com/ipfs-shipyard/ipfs-webui/pull/1685

**Pull request closed without merging**
