### PR TITLE
Feat/redesign files bar

### LINKED ISSUE #1505: Pinning integration: Solve for "pins" item in File screen info bar
_Note: This issue is part of a larger [pinning service integration epic](https://github.com/ipfs/ipfs-gui/issues/91) undertaken spring/summer 2020._

### In brief
Once pinning services are better integrated into Web UI, the "pins" item in the File screen info bar will benefit considerably from refining — either adding additional explanatory context, or repurposing altogether.

image

- [x] Discuss best-case UX for this info bar once pinning services have been added
- [x] Determine functional requirements
- [x] Draw up, discuss and agree upon UI instantiation
- [ ] Implement as a PR to close this issue, or if it's a substantial enough effort, open and resolve a new issue for implementation

This isn't critical work for MVP release, but is high on a nice-to-have list.

### PR DESCRIPTION
**Pull request by rafaelramalho19**
Closes #1505 

End result: 
image
image

### CODE REVIEW

**Comment by jessicaschilling** [comment]
That was fast 😊 
Three requests, please, per https://github.com/ipfs-shipyard/ipfs-webui/issues/1505#issuecomment-637641276 ? 
- "Files" shouldn't be clickable 
- Please remove "Pins" area entirely
- For top-level directory, keep the smaller gray text "/xxxMB"

Thank you!

**Comment by jessicaschilling** [comment]
- I don't see any reason why we need to release this any earlier than the pinning services release (whatever that one will be!): you're right, @lidel, in that we'd be removing functionality if we do it earlier. Good call.
- "all blocks" -> "all data"? "all IPFS data"? We want to make it clear that this is the difference between "your" files and all the stuff that isn't "yours" but that you're providing/reproviding to other peers. We _could_ change the "files" label to "your files" but I don't know if that's strictly correct.

**Comment by rafaelramalho19** [comment]
@lidel and @jessicaschilling should I change the merge request target to `epic/pinning-services` and merge it? That way it just ships whenever pinning services is integrated fully 😄

**Comment by jessicaschilling** [comment]
I'll leave that up to @lidel ...

**Pull request merged**
