### PR TITLE
feat: responsive nav

### PR DESCRIPTION
**Pull request by olizilla**
This is a minimal implementation of a responsive nav as part of #871 

We can go fancier in the future, but this is a minimal change to behave reasonably on small screens.

webui-responsive-navbar

On small screens, the navbar has a horizontal scroll, so you can swipe across to see the other nav items.

### CODE REVIEW

**Comment by lidel** [comment]
Switched to desktop and noticed that on my linux box there is a strange "gap" that was not present before: 

|v2.1.1 |   this PR |
| ---- | ---- | 
 |   |

**Comment by olizilla** [comment]
@lidel wat is that bar. Can you inspect it and give me any more info? I don't see it on Firefox or Chrome on mac.

**Comment by fsdiogo** [comment]
I can't reproduce it either (macOS).

**Comment by fsdiogo** [comment]
Yup, adding the class `overflow-x-hidden-l` fixes that.

I was able to reproduce that on a mac applying this settings (General):
 
scroll

**Comment by fsdiogo** [comment]
And a wild pokemon appears:

poke

**Comment by fsdiogo** [comment]
## Desktop



## Mobile

**Comment by olizilla** [comment]
@lidel the last commit from @fsdiogo should fix the scrollbar on linux, can you eyeball!

**Pull request merged**
