### PR TITLE
[wip] feat: add file status

### PR DESCRIPTION
**Pull request by hacdias**
localhost_3000_ 1

Adds the peers icons. {0, 1} is for red. {2 ... 5} for orange and > 5 for the green one.

~Altough this seems to be slowing down *a lot* the app. And despite setting the number of providers to 5, some responses have 200 and more.~

~And I find it weird that there are more people holding a file that is a medical report of mine. Am I using the API wrongly?~

~@olizilla @lidel what do you think? Could you take a look, please?~

## TODO
- [ ] Tests for the bundle

### CODE REVIEW

**Comment by hacdias** [comment]
As far as I tested, using `js-ipfs-api` with go-ipfs and js-ipfs give different results, which I don't think it's supposed. It seems that dht.findprovs is not consistent across implementations.

**Comment by olizilla** [comment]
What results did you get with js-ipfs via js-ipfs-api? last time I tried to use the `dht.findprovs` via js-ipfs directly i hit an this issue https://github.com/ipfs/js-ipfs/issues/1322 that meant no results go returned...

**Comment by hacdias** [comment]
Yes, I think it was it @olizilla

**Comment by PascalPrecht** [comment]
I'm about to send a fix for this, but as mentioned in the discussion, the API change needs some clarification.

**Comment by hacdias** [comment]
@PascalPrecht any idea of when your PR is going to be merged? 😄

**Comment by PascalPrecht** [comment]
Still awaiting feedback there as I'm struggling getting the tests for it
working :)

https://github.com/ipfs/interface-ipfs-core/pull/337#discussion_r205059048

**Comment by hacdias** [comment]
Thanks @PascalPrecht! Now we just need Go's version to be fixed so we can use it here 😄

**Comment by hacdias** [comment]
I'm closing this now due to many conflicts and this feature was postponed for the next release after 2.0.

**Pull request closed without merging**
