### PR TITLE
chore: jenkins

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Comment by hacdias** [comment]
@VictorBjelkholm what is missing here to trigger travis?

**Comment by olizilla** [comment]
@hacdias we need a Makefile for Jenkins to run

**Comment by hacdias** [comment]
Sure will take acre of that then @olizilla

**Comment by hacdias** [comment]
@olizilla I added a Makefile but it doesn't seem to trigger Jenkins. I took a look at some `js-` repos and they don't seem to have a Makefile.

**Comment by magik6k** [comment]
Jenkins does detect this - https://ci.ipfs.team/job/IPFS%20Shipyard/job/ipfs-webui/job/feat%252Fci/. You need to give write access to `ci` team on github for Jenkins to be able to set commit status.

Pipeline code is in https://github.com/ipfs/jenkins-libs/blob/master/vars/javascript.groovy

**Comment by hacdias** [comment]
Thanks @magik6k! 😄

@olizilla @VictorBjelkholm Jenkins seems to be running `commitlint`, `codelint` and `coverage` on Node 9.2.0. The newest eslint version doesn't support that node:

```
eslint@5.1.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
```

@olizilla could you take a look at why are the other tests failing? They all seem to be failing at the 'Navigation test'

**Comment by VictorBjelkholm** [comment]
@hacdias thanks. Created https://github.com/ipfs/testing/issues/56 to track it.

**Comment by olizilla** [comment]
@VictorBjelkholm any objections to re-enabling travis on this project until we fix the e2e tests and figure out if we can re-enable https://github.com/siddharthkp/bundlesize checks from jenkins?

**Comment by hacdias** [comment]
@olizilla circle!

**Comment by VictorBjelkholm** [comment]
@olizilla no objection from my side!

**Comment by olizilla** [comment]
@hacdias travis!

(we weren't publishing the coverage reporting, and I only enabled circle again to get rid of the failure reports on the PRs, we've been using travis for test and bundlesize reporting)

**Comment by hacdias** [comment]
@olizilla never noticed the .travis.yml file on this repo 😆

**Comment by hacdias** [comment]
I'm closing this for now. We can get back to Jenkins later.

**Comment by olizilla** [comment]
I'm going to redo this as a `website` job on jenkins

**Pull request closed without merging**
