### PR TITLE
More files polishing

### PR DESCRIPTION
**Pull request by hacdias**
From @olizilla (https://github.com/ipfs-shipyard/ipfs-webui/issues/748#issuecomment-414671819)

> Getting really good now! A couple of things from using the new fancy files:
> 
> - Now we've tightened up the file list, it feels like there is a little too much space at the top of the page. I don't have specific suggestions there, but what do you think?
> - The home icon with the underline seems a little to "strong" when we're at the root. It's all on it's own on the left and really dark and underlined, but it's not interesting until we start drilling down into the folders and files. Perhaps we should hide it or make it less visually distracting when we're at the root.
> - There are a few little gaps in the clickable areas on the file items. I keep managing to click right between the filename and the cid, and it's not part of the hit area so nothing happens. The is another between the icon and the file name/cid. Would be nicer to have that whole part of the box be clickable.

### CODE REVIEW

**Comment by hacdias** [comment]
@olizilla yes, there's a lot of space in the top of the page. I noticed we had two margins stacking and removed one of them.

Already fixed the clicking area.

About the home icon: I agree and personally I find the whole breadcrumbs thing too strong. Maybe a lighter color, what do you think?

**Comment by olizilla** [comment]
S C R E E N S H O T S
or
it
didn't
happen.

**Comment by hacdias** [comment]
@olizilla 😆 

image

**Comment by hacdias** [comment]
I personally liked it more saying 'Root' or 'Home' instead of having an icon

**Comment by olizilla** [comment]
@hacdias add screenshots of proposals too! Seeing the icon version side-by-side with the text version will help us decide which works best.

**Comment by hacdias** [comment]
image

image

image

image

**Comment by olizilla** [comment]
@hacdias I don't feel strongly about the icon vs the word, you pick. 

Thinking out loud, is it odd to make the last section of the breadcrumb stand out while the initial sections are faded? the initial sections are the clickable ones, so I think they should look more "clickable" than the last breadcrumb, which should look less clickable, as it's the current location. What do you think @hacdias

**Comment by hacdias** [comment]
@olizilla maybe let's stick with 'Home' for now.

Yesss, the color between faded and not faded has too much contrast. Let me see

**Comment by hacdias** [comment]
@olizilla I made the links behave and look like they do on IPLD Explorer. Every path part is a link. If you click on the path you're in, it will just do a forced refresh. It might be useful sometimes since it just updates every minute.

image

**Comment by olizilla** [comment]
@hacdias nice! Using the word Home + the colour change looks good! The breadcrumb position still seems a little off. It'll look neater if the left edge lines up with the Files colunm header, and it should match the ipld explorer. I know this deviates from the original layouts, but now we can quickly jump between the two pages it'll looks sharp if they line up across the pages too

breadcrumb-position

**Comment by hacdias** [comment]
@olizilla before that, I'm wondering whether of not is this supposed to be aligned:

image

**Comment by olizilla** [comment]
@hacdias ok, let's get this merged and I'll have a look at making making those bits more consistent.

**Pull request merged**
