### PR TITLE
fix: make analytics opt-in

### PR DESCRIPTION
**Pull request by fsdiogo**
I think this deserves a proper refactor instead of a hotfix like this one.

### CODE REVIEW

**Comment by olizilla** [comment]
Agreed. I think we an just remove the doNotTrack logic. It simplifies things.

**Comment by fsdiogo** [comment]
@olizilla this is ready for review.

TL;DR: I removed all the logic related to the `doNotTrack` setting, so analytics are disabled by default. I kept the banner asking to enable analytics when no choice has been made, after that it disappears.

**Comment by olizilla** [comment]
Ah, hold on, there is more here https://github.com/ipfs-shipyard/ipfs-webui/issues/980#issuecomment-467806732

I'll take this PR on @fsdiogo

**Comment by olizilla** [comment]
I'm gonna merge this now, so we get opt-in deployed to webui.ipfs.io now, and open an new PR for the rest.

**Pull request merged**
