### PR TITLE
wip: full screen bandwidth chart

### PR DESCRIPTION
**Pull request by hacdias**
Expand the bandwidth chart to full screen.

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

### CODE REVIEW

**Comment by hacdias** [comment]
@ipfs-shipyard/gui this is the current state:

image

Personally, I don't find it much 'attractive'. It seems top much for so little. What do you think?

**Comment by fsdiogo** [comment]
What about instead of showing it like a modal, just expand it to full width in the dashboard?

**Comment by hacdias** [comment]
@fsdiogo I also thought about that, but then what would we do with the circular graph for peers? It would be strange to have a simple circle filling 100% width of the page too

**Comment by fsdiogo** [comment]
Good question, didn't think about that 😅

**Comment by hacdias** [comment]
I'll close this one for now until we get a better idea of how to handle this. Maybe some user has ideas 😱

**Pull request closed without merging**
