### PR TITLE
feat: add ipfs config help link

### LINKED ISSUE #1110: The Config section in Settings should have a link to the documentation
**Is your feature request related to a problem? Please describe.**

The Config section in Settings is JSON in a textarea with no hints or cues about what's possible to put there.

**Describe the solution you'd like**

As an easy fix to make things better, we can add a link to the documentation of the config options.

**Describe alternatives you've considered**

More sophisticated configuration UIs are discussed in #879 and ipfs/ipfs-gui#15.

But I think we'd need to link out to the docs either way.

**Additional context**

My name is Dietrich, and I like chicken burritos.

### PR DESCRIPTION
**Pull request by hacdias**
Closes #1110. The button also has a hovering title saying 'IPFS Config Help'.

Screenshot 2019-08-16 at 09 18 20
Screenshot 2019-08-16 at 09 18 10

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

/cc @autonome

@autonome I can't set you as a reviewer... probably we need to give you permission somewhere. @olizilla do you know anything about this?

### CODE REVIEW

**Comment by hacdias** [comment]
I wonder if a teal or aqua (the same as Save) or charcoal (the same as reset) would look better.

**Comment by fsdiogo** [comment]
I wouldn't take this approach, adding a button in that specific place feels weird, as its action is not really related to the other two.

I feel this could be so much simpler, why not link to the config docs in the text description? 🤔

**Comment by hacdias** [comment]
@fsdiogo yeah, perhaps a simple link would be better and feels more cleaner. Will update.

**Comment by hacdias** [comment]
Screenshot 2019-08-16 at 12 03 28

@fsdiogo /cc

**Comment by autonome** [comment]
Yay, thanks for fixing this, text link is great solution!

**Pull request merged**
