### PR TITLE
Fix support for use behind https

### PR DESCRIPTION
**Pull request by danieldaf**
I fix and test the use of https related to the pull request #639 and the issue #611

### CODE REVIEW

**Comment by koalalorenzo** [comment]
Can't wait to get this merged (almost a month passed)

**Comment by olizilla** [comment]
We're working on a rebuild of the webui, and we'll ensure it works behind https. As a regular reminder, don't expose your API port to the public internet. That said, the current UI should work via https, so this PR is very much welcome, let's get it in!

@hacdias can you test and review this change? I think it also fixes the issue in this comment https://github.com/ipfs-shipyard/ipfs-webui/issues/653#issuecomment-385435139

**Comment by hacdias** [comment]
@olizilla gonna take a look!

**Comment by hacdias** [comment]
Seems to be working. Thanks @danieldaf

**Pull request merged**
