### PR TITLE
Zh tw

### PR DESCRIPTION
**Pull request by johnpeng968**
This is an update of zh-TW locale.

### CODE REVIEW

**Comment by lidel** [comment]
Thank you for contributing translation @johnpeng968! :+1: 

To avoid duplicated work, we don't accept direct PRs with locales.

Did you submit those translations using Transifex project at https://www.transifex.com/ipfs/ipfs-webui/ ? If not, let me know your Transifex account name, I will add you to the zh-TW translation team.

FYI there is no need for submitting PRs via GitHub: updating  them on Transifex is enough. We synchronize translations with Transifex before each release of ipfs-webui. 

You can find more information at [README#translations](https://github.com/ipfs-shipyard/ipfs-webui#translations) and [ipfs/i18n](https://github.com/ipfs/i18n).

**Comment by lidel** [comment]
@johnpeng968 I've added you to zh-TW translation team on Transifex, should be set up and ready.
Let me know if you have any questions :-)

**Comment by johnpeng968** [comment]
Thanks for letting me in. 
I downloaded 5 json files from Transifex , but lack of explore.json file in the resource list.
Not sure if someone already took it.
Please advise.

**Comment by lidel** [comment]
Explore screen is a standalone app which is also available at http://explore.ipld.io
Its translation happens in separate project: https://www.transifex.com/ipfs/ipld-explorer/

**Pull request closed without merging**
