### PR TITLE
chore: consolidate repeat-use i18n keys

### PR DESCRIPTION
**Pull request by jessicaschilling**
### Summary
This PR moves repeat-use i18n keys into `app.json`, explicitly references that namespace as needed in the appropriate files, and cleans up a few related details. This work enables more of a standardized, taxonomy-style approach as we continue to enhance functionality in Web UI overall.

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1600.

### Details
The `app.json` file now includes i18n key categories for repeat-use items:
- `actions` (things that are likely to appear on buttons and similar): 
     - `add`
     - `browse`
     - `cancel`
     - `change`
     - `clear` 
     - `close` 
     - `copy`
     - `create`
     - `delete` 
     - `download`
     - `edit`
     - `import` 
     - `more`
     - `moreInfo`
     - `noThanks`
     - `OK`
     - `pinVerb` (to distinguish between that and `terms.pinNoun` when languages differ)
     - `rename`
     - `reset` 
     - `save`
     - `saving`
     - `selectAll`
     - `submit`
     - `unpin`
     - `unselectAll`
- `nav` (things that appear in navigation furniture): 
     - `bugsLink`
     - `codeLink`
     - `revision`
- `status` (repeat-instance global status messages): 
     - `connectedToIpfs`
     - `connectingToIpfs`
     - `couldNotConnect`
- `terms` (either IPFS terms of art, or extremely common words in the Web UI context): 
     - `address`
     - `addresses`
     - `advanced` 
     - `agent` 
     - `api`
     - ` apiAddress` 
     - `blocks`
     - `connection`
     - `downSpeed` 
     - `example`
     - `file`
     - `files`
     - `folder`
     - `folders`
     - `gateway` 
     - `in`
     - `latency`
     - `location` 
     - `name`
     - `node`
     - `out`
     - `peer`
     - `peerId` 
     - `peers`
     - `pinNoun` (to distinguish between that and `actions.pinVerb` when languages differ)
     - `pins`
     - `publicKey`
     - `rateIn`
     - `rateOut` 
     - `repo`
     - `size`
     - `totalIn`
     - `totalOut`
     - `unknown`
     - `upSpeed`
- `tour` (previously existed, but didn't contain complete list of keys): 
     - `back`
     - `close`
     - `finish` 
     - `next` 
     - `skip`
     - `tooltip`

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@lidel and @rafaelramalho19 -- I'd appreciate a review at your leisure. This isn't terribly urgent work, but wanted to get this PR in sooner rather than later to avoid merge conflicts. Thank you!

**Comment by lidel** [comment]
note to self: enable preload of `en` locale to avoid raw keys to show on initial load when webui is not on local node

**Comment by jessicaschilling** [comment]
Rebased from master to account for this morning's merges, and cleaned up two additional duplicate keys. @lidel and @rafaelramalho19, this is ready for your review - thank you!

**Review by lidel — APPROVED** [review]
LGTM, let's merge this sooner than later.

**Pull request merged**
