### PR TITLE
Add webUI version in left-nav footer

### PR DESCRIPTION
**Pull request by bertrandfalguiere**
fixes https://github.com/ipfs-shipyard/ipfs-webui/issues/1649

My first Javascript fix.

Couldn't test due to https://github.com/ipfs-shipyard/ipfs-webui/issues/1650

Waiting for feedback.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Thanks @bertrandfalguiere! Got a little sidetracked on something else but will go over ASAP 😊

**Comment by jessicaschilling** [comment]
Hi @bertrandfalguiere -- https://github.com/ipfs-shipyard/ipfs-webui/pull/1654 should tighten the left nav enough to solve your visibility problem. Do you mind taking a look at that PR to confirm?

In the meantime, added a few commits to this PR for the following:
- Added version info to the Status page underneath "Agent" as we'd also discussed
- In the left nav, moved version above revision
- Adjusted i18n keys accordingly (making `version` a member of `terms` in `app.json`

Screenshot for your feedback/thoughts/ideas - and would also appreciate a review from @lidel and @rafaelramalho19 as they're able. Thank you so much!
image

**Comment by bertrandfalguiere** [comment]
Mm... I git cloned my branch, installed npm, npm installed, npm started, and now I see that on my screen:

image


So the left nav is tighter, but I still don't see revisions. 

Confirmed on Brave, Firefox, and Chrome.

I'm on Ubuntu 20.04

**Comment by jessicaschilling** [comment]
That's _really_ strange, because that style of nav (text next to icons instead of under) is a much older revision; hasn't been in master for at least a few weeks now. Are you sure you don't have an extra old copy of the project floating around your local machine?

**Comment by bertrandfalguiere** [comment]
I see what happened. I probably forked a while ago and updated this out-of-sync version. I'll fix that this evening.

**Comment by jessicaschilling** [comment]
Hey @bertrandfalguiere -- your commits from yesterday actually brought us out of sync with master 🤣 , so I'll just bring the changes into https://github.com/ipfs-shipyard/ipfs-webui/pull/1654. The work is all closely related enough to make sense as one PR, and will be a little more foolproof to test/review. Closing this PR in the meantime ... thanks again!

**Comment by bertrandfalguiere** [comment]
Yep, i saw that. I tried to work directly from Github. Will not do that ever again 🙄...

**Pull request closed without merging**
