### PR TITLE
refactor: more generic modal component

### PR DESCRIPTION
**Pull request by hacdias**
With this PR, you can now create prompts easily using always the same style. This way we don't need to be copying/pasting the classes to make them look the same.

```js
import { Prompt, PromptActions, PromptBody } from '../prompt/Prompt'
import AnIcon from '../../icons/AnIcon'

// ...

<Prompt onCancel={onCancel} >
  <PromptBody title='Example' icon={AnIcon}>
    <p className='gray w-80 center'>
  	  Lorem ipsum sin dolor amet.
    </p>
  </PromptBody>

  <PromptActions>
    <Button className='ma2' bg='bg-aqua' onClick={onDelete}>OK</Button>
  </PromptActions>
</Prompt>
```

### CODE REVIEW

**Comment by hacdias** [comment]
@olizilla sorry, it's not done yet. I found out some bugs and some stuff that is not as I'd like it to be.

**Comment by olizilla** [comment]
What is a prompt? Can haz screenshot plz?

**Comment by hacdias** [comment]
image

Maybe rename it modal?

**Comment by olizilla** [comment]
AH HA! IS A MODAL! Yes, let's call it Modal.

**Comment by hacdias** [comment]
@olizilla I'm merging this so I can use it in another PR. But it would be nice if you could take a look at the code anyway. It seems okay for me. If you find any issues, I can fix them afterwards.

**Pull request merged**
