### PR TITLE
chore: open ContextMenu on right-click

### PR DESCRIPTION
**Pull request by fsdiogo**
The ContextMenu was a standalone component but to add the ability to be opened by right-clicking a file I had to refactor it a bit and couple its logic to the File component.

Right-clicking a file now opens the context menu, but always in the default position. I've tried to open it where the user clicked but that was taking a lot of time and I don't see this as a priority right now.

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/917.

### CODE REVIEW

**Comment by hacdias** [comment]
Hmm... I like the idea of opening it with right-click but I believe it's not a good UX not to open it where we clicked.

image

Completely unexpected. I think we should give this a bit more work to open the place we click.

I found two packages that seem helpful:

- https://github.com/fkhadra/react-contexify
- https://github.com/vkbansal/react-contextmenu

If you need help, please ping me!

**Comment by fsdiogo** [comment]
> I like the idea of opening it with right-click but I believe it's not a good UX not to open it where we clicked.

I 💯 agree. I'll give this another stab today!

**Comment by fsdiogo** [comment]
The last commit opens the ContextMenu where the user right-clicked:

ctx


TODO:
- [ ] Merge and release https://github.com/tableflip/react-dropdown/pull/4 (@olizilla)
- [ ] Update `react-dropdown` in `package.json`

**Comment by fsdiogo** [comment]
This is ready for review! 🌟

**Comment by hacdias** [comment]
@fsdiogo I tried to right click and got this:

image

I made sure the dependencies were up to date.

**Comment by fsdiogo** [comment]
Hmm, just tested on Firefox and that error came up. It works on Chrome and Safari.

I'll look into it!

**Comment by fsdiogo** [comment]
Fixed!

**Comment by hacdias** [comment]
Just as a FYI, I used Chrome too, not FF. Lemme check.

**Comment by hacdias** [comment]
@fsdiogo working here and looking good. The CI is failing though both on build and navigation. :/

**Comment by olizilla** [comment]
it's a dependencies issue
```console
> ipfs-webui@2.3.2 build:darwin:linux /home/travis/build/ipfs-shipyard/ipfs-webui
> cross-env REACT_APP_GIT_REV=`git rev-parse --short HEAD` react-scripts build
Creating an optimized production build...
Failed to compile.
Module not found: Error: Can't resolve 'webcrypto-shim' in '/home/travis/build/ipfs-shipyard/ipfs-webui/node_modules/libp2p-crypto/src'

```

**Comment by olizilla** [comment]
@hacdias @fsdiogo can you confirm what versions of npm you are using pls

**Comment by hacdias** [comment]
Latest: 6.5.0

**Comment by olizilla** [comment]
reverting the unrelated changes to the package-lock.json fixes the error, so I'm going to push that change to this branch.

**Comment by fsdiogo** [comment]
Can you take a look at the code so we can merge this?

We should release a new version of Web UI ASAP to fix the add files regression.

**Pull request merged**
