### PR TITLE
chore: update navbar active item

### PR DESCRIPTION
**Pull request by fsdiogo**
As per https://github.com/ipfs-shipyard/ipfs-webui/issues/1004.

Update the way a link is active in the navbar:

nav

### CODE REVIEW

**Comment by fsdiogo** [comment]
CI is failing and I can't trigger a rebuild (no permissions) 😬

**Comment by olizilla** [comment]
@hsanjuan we're seeing the following error when using the ipfs-cluster-ctl to upload site preview in 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9c4c80]

goroutine 70 [running]:
main.main.func6.1(0xc00002b6f4, 0xc0004a0280, 0xc0000b6780)
	github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-ctl/main.go:436 +0x320
created by main.main.func6
	github.com/ipfs/ipfs-cluster/cmd/ipfs-cluster-ctl/main.go:417 +0x60f
Exited with code 2
```

is that something you've seen before?

source: https://circleci.com/gh/ipfs-shipyard/ipfs-webui/1688?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hsanjuan** [comment]
Sorry, the cluster has been offline for about 12 hours due to some raid issues, but it's back up. That said, that error is horrible. we will fix it.

**Comment by fsdiogo** [comment]
Thanks @olizilla and @hsanjuan 👍

**Comment by hsanjuan** [comment]
@olizilla actually we fixed this nil pointer panic already. It's on the 0.10.1 release.

**Comment by ericronne** [comment]
@fsdiogo awesome! Could the bar be thickened by two pixels or so, in order to stand out a little more clearly?

**Comment by fsdiogo** [comment]
@ericronne in the screenshot I posted the bar got a bit cut, can you open the site preview and see if it still needs to be thicker?

**Comment by ericronne** [comment]
@fsdiogo could you share a preview link? I'm not sure how to find it thx!

**Comment by olizilla** [comment]
@ericronne scroll to the bottom of the PR and click > "All checks have passed         -> show all checks" 

Screenshot 2019-04-26 at 18 32 11

**Comment by ericronne** [comment]
TIL❣️

**Comment by olizilla** [comment]
We should keep a record of all the styles that we use that aren't coming from atoms from ipfs-css or tachyons, so we have a list that we can use to review what should get added to ipfs-css... in the meantime 👍

**Pull request merged**
