### PR TITLE
update and translate zh-CN

### PR DESCRIPTION
**Pull request by sbilly**
- make zh-CN locales up to date
- translate

### CODE REVIEW

**Comment by hacdias** [comment]
Hello @sbilly! We're using [Transifex to manage our translations](https://github.com/ipfs-shipyard/ipfs-webui#translations), please update the translations there: 

https://www.transifex.com/ipfs/ipfs-webui/

Then we'll surely update the languages here!

**Comment by sbilly** [comment]
I can not login transifex.com with my account @ github.com

**Comment by sbilly** [comment]
I've clicked the 'join team' button.

image

**Comment by hacdias** [comment]
Hey @sbilly. I see no pending requests. Does it work now?

**Comment by sbilly** [comment]
I've finished my zh_CN translation at https://www.transifex.com . 

Can you see this? @hacdias 

image

**Comment by sbilly** [comment]
And there are no `explore.json`.

image

**Comment by hacdias** [comment]
IPLD explorer comes from here: https://www.transifex.com/ipfs/ipld-explorer/languages/

**Comment by sbilly** [comment]
@hacdias  all done.

**Comment by hacdias** [comment]
Thank you very much!

**Pull request closed without merging**
