### PR TITLE
[WIP] feat: peer country chart

### PR DESCRIPTION
**Pull request by alanshaw**
A pie chart showing the top 4 countries peers reside in.

screen shot 2018-07-18 at 15 54 07

### CODE REVIEW

**Comment by olizilla** [comment]
@alanshaw is there anything specific you wanted to add to this PR? I'll adopt it, if you wanna brain dump any todos you had in mind.

**Comment by alanshaw** [comment]
I **think** all that was left here to do here was styling. I believe the design had one segment slightly larger than the rest and tooltips instead of a key.

**Comment by hacdias** [comment]
I'll take a look at the styling then 😄

**Comment by hacdias** [comment]
image

@olizilla @alanshaw I think we should remove the labels because we can get an enormous list of countries. Otherwise we can keep them at the bottom to match #764

**Comment by olizilla** [comment]
@hacdias we need some kind of label on that graph without having to mouse over, otherwise it's just a mystery pie!

**Comment by olizilla** [comment]
Let's merge this in, and merge it in to the status page PR.

**Pull request merged**
