### PR TITLE
fix: improve color contrast on buttons

### PR DESCRIPTION
**Pull request by olizilla**
Make the add buttons bg-navy and highligh the plus symbol in aquaish

Screenshot 2019-04-24 at 11 43 24

Screenshot 2019-04-24 at 11 43 50

WIP on #1004

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
How do you like them buttons https://ipfs.io/ipfs/QmZLXLG93ZdyhnWyRLF4nEVPoGJS3oGArVPdVnvYpQi2Y2/#/files/

**Comment by ericronne** [comment]
That link fails to load for me when IPFS is running.

**Comment by fsdiogo** [comment]
> That link fails to load for me when IPFS is running.

Weird, I can open it 🤔

**Comment by ericronne** [comment]
I have *no* doubt that this glitch is specific to my machine. WebUI fails to load when my daemon is running (desktop works fine). Rather than litter this issue with my personal problems, could you paste a screenshot @olizilla? 🙏

**Pull request merged**
