### PR TITLE
feat: update to CRA 2 and Storybook 5

### PR DESCRIPTION
**Pull request by fsdiogo**
Updates to [Create React App 2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html) and [Storybook 5](https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8).

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/888 and https://github.com/ipfs-shipyard/ipfs-webui/issues/986.

### CODE REVIEW

**Comment by fsdiogo** [comment]
> We should probably still have a lint command, but that could run eslint as it's already available.

💯 agree.

> We should document that this project uses prettier, and encourage people to use an editor plugin for it. Having it format on save is pretty helpful.

I'd prefer to unburden the developers and make prettier optional.

> Should we run prettier before commit? I find any pre-commit hook quite annoying, so maybe not. But then we should double down on having folks run prettier in their editors. Same goes for eslint warning.

True, maybe we should remove prettier altogether and just use eslint.

Quick and easy, what do you think?

**Comment by olizilla** [comment]
@fsdiogo can ya update from master pls

**Comment by fsdiogo** [comment]
Synced with master @olizilla.

**Comment by olizilla** [comment]
package-lock got funky.

I can't start the app in local dev mode from an `npm ci`. am investigate.

```
./node_modules/create-hmac/browser.js
Module not found: Can't resolve 'create-hash/md5' in '/Users/oli/Code/ipfs-shipyard/ipfs-webui/node_modules/create-hmac'
```

**Comment by fsdiogo** [comment]
I used [`npm-merge-driver`](https://github.com/npm/npm-merge-driver) to automatically solve the `package-lock.json` conflicts.

You are right, doing `npm ci` is breaking the dev mode.

**Comment by olizilla** [comment]
@fsdiogo you did the right thing, but it did not do the right thing! Is working now.

**Comment by fsdiogo** [comment]
Nice! Want to shed some light of how you solved it please?

**Comment by olizilla** [comment]
@fsdiogo The error showed that `create-hmac` depends on `create-hash/md5` but looking at the files in my local `node_modules/create-hash` showed no `md5.js` which explained the error... looking at the other files in there it turned out that the entire dep was the **wrong thing**. `create-hash` was being resolved to a totally different dep:`es-to-primitive`... I did this:

```console
$ cat node_modules/create-hash/package.json 
{
    "name": "es-to-primitive",
    "version": "1.2.0",
    "author": "Jordan Harband",
    "description": "ECMAScript "ToPrimitive" algorithm. Provides ES5 and ES2015 versions.",
```

so then i was all like _whuuuuuuut!?_ so i checked the package-lock.json and found this weird nugget

```json
"create-hash": {
     "version": "1.2.0",
     "resolved": "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.0.tgz",
```

sooo, that's weird, but it at least explains why npm was dropping `es-to-primitve` in where `create-hash` should be.

the solution, well, no magic here... 

```console
$ rm -rf node_module package-lock.json
$ npm i
```
🎉 

...previously we had to be careful to preserve our package-lock.json when we were depending on an older version of ipld and a specific arrangement of ipld deps, but since we upgraded that, we're safe to re-build the package-lock when things get weird.

**Comment by fsdiogo** [comment]
betterthan

Thanks @olizilla!

**Pull request merged**
